import { ArrowDown, ArrowUpRight, Github, Linkedin, Mail } from "lucide-react";
import { PortraitScrub } from "@/components/portrait-scrub";
import { MotionSystem } from "@/components/motion-system";
import { CustomCursor } from "@/components/custom-cursor";
import { FormationLine } from "@/components/formation-line";
import { ProjectCard, type ProjectData } from "@/components/project-card";
import { ProjectOverviewSwap } from "@/components/project-overview-swap";
import { MediumArticles } from "@/components/medium-articles";
import { ContactForm } from "@/components/contact-form";
import Galaxy from "@/components/galaxy";

const projects: ProjectData[] = [
  { no: "01", title: "FreshRoute", text: "A multi-seller fresh-produce marketplace with connected inventory, ordering, payments, and fleet operations.", details: "FreshRoute connects buyers, sellers, drivers, and administrators through unified web and mobile experiences. My primary contribution covered product and inventory management, low-stock monitoring, cart operations, multi-step checkout, and order placement, including REST API integration across both applications. The wider platform supports secure payments, order batching, route optimization, delivery tracking, notifications, reviews, and operational analytics.", role: "Products, inventory, cart & ordering", stack: "React · React Native · TypeScript · Node.js · PostgreSQL · Prisma · Stripe", tone: "alpha", liveUrl: "https://freshroute-frontend.vercel.app/", images: [{ src: "/projects/freshroute/web-home.png", label: "FreshRoute web landing page" }, { src: "/projects/freshroute/web-products.png", label: "FreshRoute web product browser" }, { src: "/projects/freshroute/mobile-products.png", label: "FreshRoute mobile product browser", portrait: true }, { src: "/projects/freshroute/mobile-vendor.png", label: "FreshRoute mobile vendor dashboard", portrait: true }, { src: "/projects/freshroute/mobile-sellers.png", label: "FreshRoute mobile seller selection", portrait: true }, { src: "/projects/freshroute/mobile-tracking.png", label: "FreshRoute mobile order tracking", portrait: true }] },
  { no: "02", title: "NexaBuild", text: "A real-time floor-planning workspace with an interactive 3D interior-design experience.", details: "NexaBuild begins with an empty floor and turns imagination into space. Plans can be drawn, rooms shaped, and ideas explored in three dimensions—bringing the precision of a planning tool together with the freedom of a creative studio.", role: "Full-stack engineer", stack: "Next.js · React Three Fiber · MongoDB", tone: "orbit", liveUrl: "https://nexa-build.web.app/home/", images: [{ src: "/projects/nexabuild/home.png", label: "NexaBuild landing page" }, { src: "/projects/nexabuild/interior-3d.png", label: "NexaBuild 3D interior editor" }, { src: "/projects/nexabuild/garden-3d.png", label: "NexaBuild 3D garden editor" }, { src: "/projects/nexabuild/room-3d.png", label: "NexaBuild room layout editor" }, { src: "/projects/nexabuild/floor-plan.png", label: "NexaBuild floor-plan drawing interface" }] },
  { no: "03", title: "Haven", text: "An AI-assisted emotional wellness platform for supportive conversations, mood awareness, and relaxation.", details: "Haven combines context-aware Gemini AI conversations, mood tracking, personalized insights, and seven interactive calming exercises in one responsive experience. I built the full-stack application with secure authentication, protected routes, persistent user history, REST APIs, and light and dark interfaces. The project strengthened my experience in generative AI integration, database design, and accessible interaction design.", role: "Solo full-stack & AI project", stack: "Next.js · TypeScript · Node.js · Express · MongoDB · Gemini AI", tone: "signal", images: [{ src: "/projects/haven/landing-light.png", label: "Haven wellness platform landing page" }, { src: "/projects/haven/grounding-pause.png", label: "Haven guided grounding exercise" }, { src: "/projects/haven/dashboard.png", label: "Haven personal wellness dashboard" }, { src: "/projects/haven/mood-check-in.png", label: "Haven mood check-in response" }, { src: "/projects/haven/ai-conversation.png", label: "Haven AI wellness conversation" }, { src: "/projects/haven/calming-activities.png", label: "Haven calming activities library" }] },
  { no: "04", title: "AYA Fashion", text: "An ongoing full-stack commerce platform with a customer storefront and centralized administration for a Sri Lankan fashion brand.", details: "AYA Fashion pairs a responsive shopping experience—catalogues, collections, variants, search, cart, wishlists, and customer accounts—with an admin dashboard for managing products, inventory, orders, collections, and promotional content. I designed the backend architecture, relational data models, and REST APIs that connect the storefront and administration workflows. The ongoing project focuses on maintainability, usability, and dependable inventory and order management.", role: "Solo full-stack project · Ongoing", stack: "React · TypeScript · Node.js · Express · PostgreSQL · Prisma · Tailwind CSS", tone: "aya", images: [{ src: "/projects/aya-fashion/storefront-home.png", label: "AYA Fashion storefront landing page" }, { src: "/projects/aya-fashion/cart-drawer.png", label: "AYA Fashion shopping bag drawer" }, { src: "/projects/aya-fashion/checkout.png", label: "AYA Fashion checkout and order summary" }, { src: "/projects/aya-fashion/inventory-dashboard.png", label: "AYA Fashion product inventory dashboard" }, { src: "/projects/aya-fashion/product-editor.png", label: "AYA Fashion product and stock editor" }, { src: "/projects/aya-fashion/aya-logo.png", label: "AYA Fashion brand identity", portrait: true }] },
  { no: "05", title: "RythmoBot", text: "A music-synchronized dancing robot combining embedded control, environmental sensors, and a real-time web interface.", details: "RythmoBot was developed for a Microcontroller-Based System Design project using an ESP32 and PCA9685 controller to coordinate servo-driven leg, arm, and head movements. Sound and ultrasonic sensors enable clap and obstacle responses, while WS2812B LEDs, an I2C display, and a buzzer provide visual and audio feedback. A Wi-Fi and WebSocket control interface lets users select songs and trigger choreographed sequences in real time.", role: "Embedded systems & web group project", stack: "ESP32 · C/C++ · PCA9685 · WebSockets · I2C · Sensors & actuators", tone: "rythmo", images: [{ src: "/projects/rythmobot/robot-front.jpeg", label: "RythmoBot assembled robot", portrait: true }, { src: "/projects/rythmobot/robot-lit.jpeg", label: "RythmoBot illuminated during testing", portrait: true }, { src: "/projects/rythmobot/web-app.png", label: "RythmoBot real-time web control interface" }, { src: "/projects/rythmobot/technical-poster.png", label: "RythmoBot technical architecture poster", portrait: true }] },
  { no: "06", title: "Hadathala", text: "A responsive online ticket-booking experience created for the Hadathala annual dance concert.", details: "Hadathala carries the anticipation of a live performance into the booking experience. Built for an annual dance concert, it guides audiences from discovery to reservation through a responsive interface shaped by rhythm, clarity, and celebration.", role: "Frontend & UX · Group project", stack: "React · Tailwind CSS · Node.js · SQL", tone: "hadathala", images: [{ src: "/projects/hadathala/landing-page.png", label: "Hadathala dance concert landing page" }, { src: "/projects/hadathala/seating-plan.png", label: "Hadathala seating plan and ticket tier selection" }] },
];

export default function Home() {
  return <>
    <div className="galaxy-background"><Galaxy mouseRepulsion mouseInteraction density={1} glowIntensity={0.3} saturation={0} hueShift={140} twinkleIntensity={0.3} rotationSpeed={0.1} repulsionStrength={2} autoCenterRepulsion={0} starSpeed={0.5} speed={1} /></div>
    <MotionSystem /><CustomCursor /><FormationLine />
    <header className="site-header"><a className="brand" href="#top" aria-label="Tharuki Vinodya home">TV.</a><nav aria-label="Primary navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#skills">Skills</a><a href="#articles">Articles</a><a href="#contact">Contact</a></nav></header>
    <main id="top">
      <section className="hero wrap formation-node" aria-labelledby="hero-title">
        <div className="hero-copy"><p className="eyebrow">Software engineer intern / Sri Lanka</p><h1 id="hero-title">Tharuki<br />Vinodya</h1><p className="intro">I build thoughtful web and mobile systems where clarity, people, and motion meet.</p><div className="actions"><a className="button primary" href="#work">View my work</a><a className="button secondary" href="#contact">Contact me</a></div></div>
        <PortraitScrub />
        <a className="scroll-cue" href="#about" aria-label="Continue to about"><ArrowDown size={16} /></a>
      </section>

      <div className="rhythm-strip" aria-label="Core technologies"><div><span>React</span><i /><span>Next.js</span><i /><span>TypeScript</span><i /><span>Node.js</span><i /><span>React Native</span><i /><span>PostgreSQL</span><i /><span>Accessible by design</span><i /></div></div>

      <section id="about" className="about wrap section formation-node" aria-labelledby="about-title"><p className="section-label">01 / About</p><div><h2 id="about-title" data-reveal>I build reliable software for real-world problems.</h2><div className="formation-underline" aria-hidden="true" /><div className="about-details"><p data-reveal>Information Technology undergraduate at the University of Moratuwa, passionate about building practical software solutions across full-stack, mobile, and intelligent systems.</p><dl data-reveal><div><dt>Education</dt><dd>BSc (Hons) Information Technology</dd></div><div><dt>Focus</dt><dd>Web, mobile & intelligent systems</dd></div></dl></div></div></section>

      <section id="work" className="work wrap section formation-node" aria-labelledby="work-title"><p className="section-label">02 / Selected work</p><h2 id="work-title" className="sr-only">Selected projects</h2><ProjectOverviewSwap projects={projects} /><p className="project-list-label">Project details</p><div className="project-list">{projects.map((project) => <ProjectCard project={project} key={project.no} />)}</div></section>

      <section id="skills" className="skills wrap section formation-node" aria-labelledby="skills-title"><p className="section-label">03 / Skills in formation</p><div><h2 id="skills-title" data-reveal>Tools move into place.</h2><div className="formation-branches" aria-hidden="true"><i /><i /><i /></div><div className="skill-groups"><Skill title="Frontend & Mobile" items={["React", "Next.js", "React Native", "TypeScript", "Tailwind CSS"]} /><Skill title="Backend & Data" items={["Node.js", "Express.js", "PostgreSQL", "MongoDB", "Prisma ORM"]} /><Skill title="Tools & Systems" items={["Git & GitHub", "Docker", "Gemini AI", "WebSockets", "Figma"]} /></div></div></section>

      <section id="articles" className="articles wrap section formation-node" aria-labelledby="articles-title"><div className="articles-heading"><p className="section-label">04 / Writing</p><h2 id="articles-title" data-reveal>Ideas, explored in words.</h2><p>Notes on software engineering, design, and the things I learn while building.</p><a href="https://medium.com/@vinodyatharuki" target="_blank" rel="noreferrer">View Medium profile <ArrowUpRight size={16} /></a></div><MediumArticles /></section>

      <section id="contact" className="contact-section wrap section formation-node" aria-labelledby="contact-title"><div className="contact-heading"><p className="section-label">05 / Contact</p><div><h2 id="contact-title" data-reveal>Let&apos;s build something clear.</h2><p>Have a project, an opportunity, or simply an idea worth discussing? I&apos;d love to hear from you.</p></div></div><div className="contact-details"><a href="mailto:vinodyatharuki@gmail.com"><Mail size={20} /><span>Email</span><i aria-hidden="true">→</i><strong>vinodyatharuki@gmail.com</strong></a><a href="https://www.linkedin.com/in/tharuki-vinodya-0357a0310/" target="_blank" rel="noreferrer"><Linkedin size={20} /><span>LinkedIn</span><i aria-hidden="true">→</i><strong>Tharuki Vinodya</strong></a></div><ContactForm /></section>
    </main>
    <footer className="site-footer"><div className="wrap"><p>© {new Date().getFullYear()} Tharuki Vinodya</p><div className="social"><a href="https://github.com/TharukiTV" target="_blank" rel="noreferrer" aria-label="GitHub"><Github /></a><a href="https://www.linkedin.com/in/tharuki-vinodya-0357a0310/" target="_blank" rel="noreferrer" aria-label="LinkedIn"><Linkedin /></a><a href="mailto:vinodyatharuki@gmail.com" aria-label="Email"><Mail /></a></div></div></footer>
  </>;
}

function Skill({ title, items }: { title: string; items: string[] }) { return <div className="skill-group"><h3>{title}</h3>{items.map(item => <span className="skill-token" key={item}>{item}</span>)}</div>; }
